services:
  - type: web
    name: astrovoice-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main_openai_realtime.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
    healthCheckPath: /health
